create table if not exists teams(
  id INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR NOT NULL UNIQUE,
  logo VARCHAR,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME DEFAULT CURRENT_TIMESTAMP
);

create table if not exists games(
  id INTEGER NOT NULL PRIMARY KEY,
  data VARCHAR,
  status INT DEFAULT 0,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME DEFAULT CURRENT_TIMESTAMP
);

create table if not exists logs(
  id INTEGER NOT NULL PRIMARY KEY,
  game_id INTEGER,
  msg VARCHAR,
  clock VARCHAR,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(game_id) REFERENCES games(id)
);
